<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="10.1.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
		<PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="xunit.v3" Version="4.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CaseTrack.Api\CaseTrack.Api.csproj" />
		<ProjectReference Include="..\CaseTrack.Application\CaseTrack.Application.csproj" />
		<ProjectReference Include="..\CaseTrack.Domain\CaseTrack.Domain.csproj" />
		<ProjectReference Include="..\CaseTrack.Infrastructure\CaseTrack.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

</Project>
